### ISSUE TITLE
 mBetaGenetic

### ISSUE THREAD

**Issue by oceallc** [HannahVMeyer/PhenotypeSimulator#12]
I'm confused by the mBetaGenetic parameter which is the mean of the effect sizes of the genetic variants distribution. I would imagine a higher value means the effect of the causal variants is greater on the phenotype, but shouldn't this be decided by only the values for genVar and cNrSNP? I've tried playing around with different values for the parameter and it doesn't seem to affect the final phenotype values? Could someone give me an intuitive view of what mBetaGenetic is setting? Thank you.

**Comment by HannahVMeyer** [comment]
the mBetaGenetic parameter specifies the mean of the distribution from which the effect sizes of each of the causal variants are drawn from. The genVar specifies the proportion of the total amount of variance that both the infinitesimal and variant effects contribute to the phenotype.

```
beta2 <- runSimulation(N=1000, P=3, mBetaGenetic=2, genVar=0.4, h2s=1, phi=1,
                    cNrSNP=10, tNrSNP = 10, pTraitIndependentGenetic=0,
                    pIndependentGenetic=0, seed=5)
mean(beta2$phenoComponentsIntermediate$genFixed$cov_effect)
[1] 2.149688

beta0 <- runSimulation(N=1000, P=3, mBetaGenetic=0, genVar=0.4, h2s=1, phi=1,
                    cNrSNP=10, tNrSNP = 10, pTraitIndependentGenetic=0, seed=5)
mean(beta0$phenoComponentsIntermediate$genFixed$cov_effect)
[1] 0.1315467
```

**Comment by HannahVMeyer** [comment]
I am closing this now, let me know if you have additional questions about this.
