### ISSUE TITLE
getCausalSNPs() doesn't identify single causal SNP

### ISSUE THREAD

**Issue by SarahNadeau** [HannahVMeyer/PhenotypeSimulator#13]
getCausalSNPs() does not identify which SNP is causal when only a single causal SNP is specified. To demonstrate the problem:

getCausalSNPs(NrCausalSNPs = 1, ...) gives:
          [,1]
ID_1      0
ID_2     0
ID_3     0

while getCausalSNPs(NrCausalSNPs = 2, ...) gives the more helpful:
      SNP_6 SNP_7
ID_1       0     0
ID_2      0     0
ID_3      0     0

I believe this problem is a result of this line in the getCausalSNPs function:
causalSNPs <- genotypes$genotypes[, sort(sample(ncol(genotypes$genotypes), 
                                      NrCausalSNPs))]

**Comment by HannahVMeyer** [comment]
Hi Sarah,

thank you for pointing this out. I have fixed the issue now.

Hannah

**Comment by SarahNadeau** [comment]
Great, thanks so much!
