### ISSUE TITLE
how exclude "non-genetic covariate effects" in simulating phenotypes

### ISSUE THREAD

**Issue by fmoradi1365** [HannahVMeyer/PhenotypeSimulator#16]
Hello,

I am using your PhenotypeSimulator package in my research and have a few questions:

I am interested in generating phenotypes as the sum of "genetic variant effects", and "observational noise effects". I do not want to consider "non-genetic covariate effects", but I think in the R codes I need to set parameter "shared" to a proportion of nongenetic covariates being shared across all traits to be able to include "observational noise effects" in the model. In this case, I think I should set the parameter "shared" to zero, but, based on R codes, it is not possible. Would it be possible to guide me to tackle this issue?

genVar <-         #proportion of genetic variance
noiseVar <- 1- genVar   #proportion variation defined by noise 
shared <-           #proportion of nongenetic covariate shared across all trait
independent <- 1 - shared   #proportion of independent nongenetic covariate 

# rescale phenotype components
genBg_shared_scaled <- rescaleVariance(genBg$shared, shared * genVar)
genBg_independent_scaled <- rescaleVariance(genBg$independent, independent * genVar)
noiseBg_shared_scaled <- rescaleVariance(noiseBg$shared, shared * noiseVar)
noiseBg_independent_scaled <- rescaleVariance(noiseBg$independent, independent *noiseVar)

Many thanks for your time.

**Comment by HannahVMeyer** [comment]
I would recommend using the `runSimulation` function in PhenotypeSimulator. From its documentation:
```r
 ?PhenotypeSimulator::runSimulation
[...]
noiseVar    Proportion [double] of total noise variance.
rho         Proportion [double] of noise variance of correlated effects;
            sum of rho, delta and phi has to be equal 1.
delta       Proportion [double] of noise variance of non-genetic covariate effects;
            sum of rho, delta and phi has to be equal 1.
phi         Proportion [double] of noise variance of observational noise effects;
            sum of rho, delta and phi has to be equal 1.
```
With `noiseVar` you can specify the proportion of phenotypic variance explained by ALL non-genetic terms i.e. non-genetic covariate effect, non-genetic correlation effects and observational noise. If you do not want to include any of these in your phenotypes simply set the corresponding proportion to 0 and make sure that the sum of all comments is equal to 1. For instance, if you want all non-genetic variance to be explained by observational noise, set `phi=1`, `delta=0` and `rho=0`.

Generally, I would recommend looking at the documentation and extensive vignettes and explanations provided on this page (documentation drop-down menu): https://hannahvmeyer.github.io/PhenotypeSimulator/

**Comment by fmoradi1365** [comment]
Hi Hannah,

Thanks very much for the clarification.

**Comment by HannahVMeyer** [comment]
You are welcome, glad it is useful!
