### ISSUE TITLE
License question

### ISSUE THREAD

**Issue by bambrozio** [HannahVMeyer/PhenotypeSimulator#19]
Nice work!
I was looking for a phenotype simulator that can generate both case/controls and quantitative traits against a real genomic dataset like 1000 genomes. Googling it I came across this repository.
There's any reason you're not using a standard open-source license, like MIT?

**Comment by HannahVMeyer** [comment]
I am using an MIT LICENSE: see the [Description](https://github.com/HannahVMeyer/PhenotypeSimulator/blob/master/DESCRIPTION) file and an explanation for the additional license file from [here](http://r-pkgs.had.co.nz/description.html#license):

MIT (v. similar: to BSD 2 and 3 clause licenses). This is a simple and permissive license. It lets people use and freely distribute your code subject to only one restriction: the license must always be distributed with the code.

The MIT license is a “template”, so if you use it, you need License: MIT + file LICENSE, and a LICENSE file that looks like this:
```
YEAR: <Year or years when changes have been made>
COPYRIGHT HOLDER: <Name of the copyright holder>
```

**Comment by bambrozio** [comment]
Ah! cool. Sorry about that. I saw only the file: https://github.com/HannahVMeyer/PhenotypeSimulator/blob/master/LICENSE 
Thanks! :)

**Comment by HannahVMeyer** [comment]
No problem
