### ISSUE TITLE
Missing CEU haplotype data from vignette

### ISSUE THREAD

**Issue by zfuller5280** [HannahVMeyer/PhenotypeSimulator#24]
It appears the CEU haplotype data originally found on the [impute2](https://mathgen.stats.ox.ac.uk/impute/impute_v1.html#Using_IMPUTE_with_the_HapMap_Data) webpage is no longer available for download, making it not possible to follow the power analysis example [vignette](https://hannahvmeyer.github.io/PhenotypeSimulator/articles/Simulation-and-LinearModel.html). There are correctly formatted haplotype files in hg19 coordinates still available on one of the impute [webpages](https://mathgen.stats.ox.ac.uk/impute/data_download_1000G_phase1_integrated.html), however these contain reference haplotypes for 1,092 individuals from multiple populations. To filter these haplotypes for only CEU samples, following a suggestion on the impute docs, the column numbers corresponding to each sample/population can be found in the file `ALL_1000G_phase1integrated_v3.sample` and `cut` can be used to subset these.

`cat ALL_1000G_phase1integrated_v3.sample|grep -Fn CEU`

CEU individuals are from columns 413-497. 

```
for chr in `seq 1 22`; do
      cut -f413-497 -d" " ALL_1000G_phase1integrated_v3_${chr}_impute_macGT1.hap > ${chr}.ceu_subset.hap
done
```
So far, this appears to work and makes it possible to run hapgen2 following the example described in the vignette. I will update further if I run into additional issues using the new data.

**Comment by HannahVMeyer** [comment]
Thanks for pointing this out Zach! I will incorporate the news links and processing steps into the vignette. I'll keep the issue open till I've pushed changes and resubmitted to CRAN.

Thanks!
