### ISSUE TITLE
Command line function seems to do nothing with the --genotypefile argument

### ISSUE THREAD

**Issue by HussainMSajwani** [HannahVMeyer/PhenotypeSimulator#27]
Hi. I am Hussain Sajwani, a research assistant to Dr. Samuel Feng at Khalifa University, Abu Dhabi. 

When using the command line function `simulatePhenotypes()`, it seems that nothing is done with the `--genotypefile` argument. For example, running
```
Rscript -e "PhenotypeSimulator::simulatePhenotypes()" \
        --args \
	--NrSamples=1000 --NrPhenotypes=1 \
	--tNrSNP=1000 \
	--genotypefile=plinkfile --format=plink \
	--cNrSNP=10 \
	--genVar=0.95 --h2s=$(h2s) --phi=1 \
	--directory=/home/shussain/PS \
	--subdirectory=output \
	--showProgress \
	--saveTable \
	--savePLINK
```
with "plinkfile" being any binary PLINK file (with .bed, .bim, and .fam files), seems to ignore the provided genotype file and simulate a genotype of its own. This can be confirmed by tracing what happens with the `--genotype` argument in the `simulatePhenotypes()` function. https://github.com/HannahVMeyer/PhenotypeSimulator/blob/master/R/commandlineFunctions.R.
This is on `PhenotypeSimulator` version 0.3.3.

**Comment by HannahVMeyer** [comment]
Thanks for raising this issue; the genotypefile flag was indeed not passed on.

Can you try installing the development version? I just pushed the change to this branch: 

```r
library(devtools)
install_github("HannahVMeyer/PhenotypeSimulator", ref="dev" )
```

**Comment by HussainMSajwani** [comment]
This works now. Thanks!
