### ISSUE TITLE
Help with simulator options

### ISSUE THREAD

**Issue by lsmainzer** [HannahVMeyer/PhenotypeSimulator#8]
Hello!

We need to create a variety of simulated GWAS datasets (geno and pheno matrices) with increasing number of SNPs and individuals, to scale-up and benchmark our GWAS software. Your simulator seems very attractive! We just have a few questions about it's usage:

1) can it produce simulated genotype and phenotype matrices from scratch, without a real dataset to start with?
2) can user specify the size of final dataset, i.e. 50,000 SNPs and 10,000 individuals? 
3) it's hard to tell from the README what is the full set of input options and what the outputs would be.  Could you please help with that? 

We have looked at your paper, very nice!  Just need help with actual software.
Thanks a lot,
Liudmila Mainzer

**Comment by HannahVMeyer** [comment]
Hi!

I am travelling at the moment and will get back to you by Wednesday this week.

Glad to hear it will be useful for you and would be happy to get some input on how to make the documentation clearer.

Cheers,
Hannah

**Comment by lsmainzer** [comment]
Thanks a lot! 

Right now mainly we need to know whether it can simulate from scratch, and how do we tell it the number of SNPs and individuals we need. 

I found the manual on CRAN (https://cran.r-project.org/web/packages/PhenotypeSimulator/PhenotypeSimulator.pdf), and it is very extensive, thank you very much! I think just linking to that from Github would help a lot.

From the manual I gather one can run simulatePhenotypes() with input options --NrSamples=100 --NrPhenotypes=15 --tNrSNPs=10000 --cNrSNPs=30. That helps. Not clear if we should run simulateGenotypes first though. I think just an example usage statement for the entire package, using a very simple example, would help. 

Regards,
Liudmila Mainzer

**Comment by HannahVMeyer** [comment]
HI Liudmila,

if you run 
```
Rscript -e "PhenotypeSimulator::simulatePhenotypes()" \
--args \
--NrSamples=100 --NrPhenotypes=15 \
--tNrSNP=10000 --cNrSNP=30 \
--SNPfrequencies=0.05,0.1,0.3,0.4 \
--genVar=0.4 --h2s=0.1 --phi=0.6 --delta=0.4 
--...
```

or from within R
```
simulate <- runSimulation(N=100, P=15, tNrSNPs=10000, cNrSNPs=30, 
genVar=0.4, h2s=0.1, delta=0.4, phi=0.6)
```
PhenotypeSimulator will simulate genotypes from scratch and will use those for the genetic components of the phenotypes. However, as stated in the [paper](https://academic.oup.com/bioinformatics/article/34/17/2951/4956348), 

    PhenotypeSimulator can simulate simple bi-allelic SNPs, where each SNP is
    simulated from a binomial distribution with two trials and probability equal to
    the given allele frequencies [as for instance used in (Lippert et al., 2013)].
    This simple approach, however, does not simulate any dependency between
    the genotypes as is observed with LD structure in the genome. To allow for 
    more complex genotype structures, PhenotypeSimulator can import genotypes
    generated from different genotype simulation software, covering genotypes
    simulated from coalescent models  GENOME (Liang et al., 2007), a
    re-sampling-based approach HAPGEN2 (Su et al., 2011) and differ- 
    ent forward-time approaches delimited-formats as given by simuPOP
    (Peng and Kimmel, 2005),  ForSim (Lambert et al., 2008) and
    GenomePop2 (Carvajal-Rodrı´guez, 2008).

For GWAS-like applications, LD structure is likely to be important, so I would recommend using an external simulation software like Hapgen2 to first simulate genotypes and then provided those genotypes to PhenotypeSimulator. 

Have a look at this [vignette](https://github.com/HannahVMeyer/PhenotypeSimulator/blob/master/inst/doc/Simulation-and-LinearModel.pdf), showing the workflow from genotype simulation with hapgen, to phenotype simulation and subsequent GWAS.

Let me know if anything else needs clarification.

Also, I am about to release a new version to CRAN. I have updated some input checking and would recommend downloading the latest version from github via: 

```
library(devtools)
install_github("HannahVMeyer/PhenotypeSimulator")
```

Cheers,
Hannah

**Comment by HannahVMeyer** [comment]
I have added a link to the full [documentation](http://HannahVMeyer.github.io/PhenotypeSimulator/) and the [vignettes](https://hannahvmeyer.github.io/PhenotypeSimulator/articles), so information on usage will hopefully be easier to find in the future. I am closing this issue for now, feel free to re-open if you need more information.

**Comment by lsmainzer** [comment]
Hello, Hannah!

Thank you very much, this explains a lot. I did find your vignettes on CRAN, and the manual. We are poking through them. Very detailed, thank you!

Just one question, to confirm: there is no possibility to simulate phenotypes that are affected by epistasis? 

How difficult do you think it would be to add that functionality? No promises, but if it's not too hard, with a bit of guidance from you, perhaps we might be able to contribute ...

Thanks a lot,
Liudmila Mainzer

**Comment by HannahVMeyer** [comment]
Hi Liudmila,

yes, at the moment there is no possibility to simulate epistasis.  In theory, it should only be one additional option/function in the geneticFixedEffect simulation.
I am quite busy at the moment, but might have some time towards the end of the week to look into it.

Do you have any epistasis model in mind?
 
Cheers,
Hannah

**Comment by HannahVMeyer** [comment]
Hi Liudmila,

yes, at the moment there is no possibility to simulate epistasis. In theory, it should only be one additional option/function in the geneticFixedEffect simulation.
I am quite busy at the moment, but might have some time towards the end of the week to look into it.

Do you have any epistasis model in mind?

Cheers,
Hannah

**Comment by lsmainzer** [comment]
Hi folks,

First off - it is nice to meet you Hannah. Thank you for developing the PhenotypeSimualtor package. Thank you also for considering the possibility of adding the possibility of simulating epistatic effects between alleles at two loci. For the time being, we are considering additive x additive epistatic effects, and I think this would be a logical starting point. In the future, I think that also considering additive x dominance, dominance x additive, and dominance x dominance (and eventually higher-order iterations) would be also interesting.

Best wishes,

Alex

Alexander E. Lipka, PhD
Assistant Professor of Biometry
Department of Crop Sciences
University of Illinois
W-201A Turner Hall
1102 S Goodwin Ave
Urbana IL 61801
alipka@illinois.edu<mailto:alipka@illinois.edu>

Phone: +1-217-300-0726
http://publish.illinois.edu/thelipkalab/









On Nov 5, 2018, at 8:25 AM, Liudmila Sergeevna Mainzer <lmainzer@life.illinois.edu<mailto:lmainzer@life.illinois.edu>> wrote:



Thanks, Hannah! I am bringing our colleague Dr. Alexander Lipka into this conversation, he is a statistician and a population geneticist.

Alex: I have made the suggestion to Hannah, the author of the PhenotypeSimulator package, that perhaps epistasis be added into it. She might have time to investigate how easy or difficult that might be, but wants to know if there are any epistasis models we would particularly favor.

Looking for ward to any comment.

Luda






On 11/5/2018 1:21 AM, HannahVMeyer wrote:

Hi Liudmila,

yes, at the moment there is no possibility to simulate epistasis. In theory, it should only be one additional option/function in the geneticFixedEffect simulation.
I am quite busy at the moment, but might have some time towards the end of the week to look into it.

Do you have any epistasis model in mind?

Cheers,
Hannah

**Comment by HannahVMeyer** [comment]
I will close this issue as I have not been able to implement this. Maybe this simulation tool could be of help: https://cran.r-project.org/web/packages/simplePHENOTYPES/index.html
