### ISSUE TITLE
getCausalSNPs from oxgen format

### ISSUE THREAD

**Issue by blairzhang126** [HannahVMeyer/PhenotypeSimulator#9]
I have trouble to get this function work for oxgen format. My command is:

"causalSNPs <- getCausalSNPs(N=6000, NrCausalSNPs=10, chr=22,genoFilePrefix="geno_case_", genoFileSuffix=".gen", format="oxgen", NrSNPsOnChromosome=119317)"

The error message I got is "Error in `.rowNamesDF<-`(x, value = value) : invalid 'row.names' length". 
My guess is that if I use suffix as ".gen" it cannot read ".sample" file so that the row.names is invalid. However, I cannot proceed without suffix flag. Any idea?

Any feedback would be greatly appreciated. 

Thanks so much Hannah.
-Blair

**Comment by HannahVMeyer** [comment]
Hi Blair,

at the step that I suspect it is failing, the sample IDs (contained in the .sample) file are not needed yet, so this won't be the issue. 

Can you paste the first 10 columns and lines of the file that is failing ie from geno_case_chr22.gen?

**Comment by blairzhang126** [comment]
Thank you so much for the quick reply Hannah.

My first few lines look like this (I added "22-" after it's not working on the original hapgen2 output):
22-snp_0 rs62224609 14431249 T C 1 0 0 1 0 0 1 0 0 0 1 0 1 0 0 1 0 0 1 0 0
22-snp_1 rs11089130 14431347 G C 1 0 0 1 0 0 1 0 0 1 0 0 1 0 0 1 0 0 1 0 0
22-snp_2 rs11089134 14431497 A G 1 0 0 0 1 0 0 1 0 1 0 0 1 0 0 1 0 0 1 0 0
22-snp_3 rs2096600 14431968 C A 1 0 0 1 0 0 1 0 0 1 0 0 1 0 0 1 0 0 1 0 0 
22-snp_4 rs9604696 14431994 C T 1 0 0 1 0 0 1 0 0 1 0 0 1 0 0 1 0 0 1 0 0 
22-snp_5 rs4965031 14432080 G A 1 0 0 1 0 0 1 0 0 1 0 0 1 0 0 1 0 0 0 1 0 
22-snp_6 rs2843214 14432239 A G 1 0 0 1 0 0 1 0 0 1 0 0 1 0 0 1 0 0 0 1 0 
22-snp_7 rs4965018 14432361 A G 1 0 0 1 0 0 1 0 0 1 0 0 1 0 0 1 0 0 0 1 0 
22-snp_8 rs2078643 14432513 G C 1 0 0 1 0 0 1 0 0 1 0 0 0 1 0 0 1 0 0 1 0 
22-snp_9 rs738829 14432618 G A 1 0 0 1 0 0 1 0 0 1 0 0 1 0 0 1 0 0 1 0 0 1

**Comment by blairzhang126** [comment]
I got it working when I transform my file format into the space-delimited format and follow the example you gave for .csv file. So don't worry about it if it requires a lot of time and work to get it working on oxgen format if I'm the only person who got this error. Thanks again for your help Hannah. Feel free to keep me posted on any thing related to this.

**Comment by HannahVMeyer** [comment]
I've just made changes in the develop branch. Could you check if it works after you do:
devtools::install_github('HannahVMeyer/PhenotypeSimulator', ref='dev’)

Thanks

**Comment by blairzhang126** [comment]
Hi Hannah, I got an error: "Error in getCausalSNPs(N = 100, NrCausalSNPs = 10, chr = 22, genoFilePrefix = "test_time_",  : 
  object 'samples' not found".

**Comment by blairzhang126** [comment]
My script: "causalSNPs <- getCausalSNPs(N=100, NrCausalSNPs=10, chr=22,genoFilePrefix="test_time_", genoFileSuffix="_100_out.controls.gen",NrSNPsOnChromosome = 119316, format="oxgen")"

**Comment by HannahVMeyer** [comment]
Apologies for the late reply - I will look into it this week. Thanks

**Comment by HannahVMeyer** [comment]
This fixed now on github version 0.3.2. I will keep the issue open until this has been updated on CRAN.

**Comment by HannahVMeyer** [comment]
Latest release including this fix on CRAN (v0.3.3), closing this now.
